#! /bin/sh

bspc config border_width        1
bspc config window_gap         14

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor DVI-I-2  -d L1 L2 L3
bspc monitor HDMI-0   -d R1 R2 R3
