#! /bin/sh

bspc config border_width               1
bspc config window_gap                12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config pointer_follows_focus   true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer   true

bspc monitor DVI-I-2  -d L1 L2 L3
bspc monitor DVI-I-3   -d R1 R2 R3

bspc rule -a Skype desktop=^1
bspc rule -a obs desktop=^3
